"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const compression_1 = __importDefault(require("compression"));
const dotenv_1 = __importDefault(require("dotenv"));
const cookie_parser_1 = __importDefault(require("cookie-parser"));
// import router from './routes';
const app = (0, express_1.default)();
const { env: { PORT, NODE_ENV }, } = process;
dotenv_1.default.config();
app.set('port', PORT || 5000);
app.use(express_1.default.json());
app.use(express_1.default.urlencoded({ extended: false }));
app.use((0, compression_1.default)());
app.use((0, cookie_parser_1.default)());
console.log('dev');
exports.default = app;
