name: Test Suits Routes
on: push
env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:16

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: 123456
          POSTGRES_USER: team5
          POSTGRES_DB: bms_testing
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Testing Routes
        run: npm test
        env:
          TEST_DB_URL: postgres://team5:123456@localhost:5432/bms_testing

      - name: Lint Action
        uses: wearerequired/lint-action@v2.0.0